"""
This type stub file was generated by pyright.
"""

def newer_pairwise_group(sources_groups, targets): # -> tuple[list[Unknown], list[Unknown]]:
    """Walk both arguments in parallel, testing if each source group is newer
    than its corresponding target. Returns a pair of lists (sources_groups,
    targets) where sources is newer than target, according to the semantics
    of 'newer_group()'.
    """
    ...

