"""
This type stub file was generated by pyright.
"""

have_pyrex = ...
_Extension = ...
class Extension(_Extension):
    """Extension that uses '.c' files in place of '.pyx' files"""
    def __init__(self, name, sources, *args, **kw) -> None:
        ...
    


class Library(Extension):
    """Just like a regular Extension, but built as a library instead"""
    ...


