"""
This type stub file was generated by pyright.
"""

"""
Filename globbing utility. Mostly a copy of `glob` from Python 3.5.

Changes include:
 * `yield from` and PEP3102 `*` removed.
 * Hidden files are not ignored.
"""
def glob(pathname, recursive=...): # -> list[Unknown | bytes | str]:
    """Return a list of paths matching a pathname pattern.

    The pattern may contain simple shell-style wildcards a la
    fnmatch. However, unlike fnmatch, filenames starting with a
    dot are special cases that are not matched by '*' and '?'
    patterns.

    If recursive is true, the pattern '**' will match any files and
    zero or more directories and subdirectories.
    """
    ...

def iglob(pathname, recursive=...): # -> Generator[Unknown | bytes | str, None, None]:
    """Return an iterator which yields the paths matching a pathname pattern.

    The pattern may contain simple shell-style wildcards a la
    fnmatch. However, unlike fnmatch, filenames starting with a
    dot are special cases that are not matched by '*' and '?'
    patterns.

    If recursive is true, the pattern '**' will match any files and
    zero or more directories and subdirectories.
    """
    ...

def glob1(dirname, pattern): # -> List[bytes]:
    ...

def glob0(dirname, basename): # -> list[Unknown]:
    ...

def glob2(dirname, pattern): # -> Generator[Unknown | bytes | str, None, None]:
    ...

magic_check = ...
magic_check_bytes = ...
def has_magic(s): # -> bool:
    ...

def escape(pathname):
    """Escape all special characters.
    """
    ...

