"""
This type stub file was generated by pyright.
"""

def fetch_build_egg(dist, req): # -> Distribution:
    """Fetch an egg needed for building.

    Use pip/wheel to fetch/build a wheel."""
    ...

def strip_marker(req): # -> Requirement:
    """
    Return a new requirement without the environment marker to avoid
    calling pip with something like `babel; extra == "i18n"`, which
    would always be ignored.
    """
    ...

