"""
This type stub file was generated by pyright.
"""

import platform
from os import environ

"""
Improved support for Microsoft Visual C++ compilers.

Known supported compilers:
--------------------------
Microsoft Visual C++ 9.0:
    Microsoft Visual C++ Compiler for Python 2.7 (x86, amd64)
    Microsoft Windows SDK 6.1 (x86, x64, ia64)
    Microsoft Windows SDK 7.0 (x86, x64, ia64)

Microsoft Visual C++ 10.0:
    Microsoft Windows SDK 7.1 (x86, x64, ia64)

Microsoft Visual C++ 14.X:
    Microsoft Visual C++ Build Tools 2015 (x86, x64, arm)
    Microsoft Visual Studio Build Tools 2017 (x86, x64, arm, arm64)
    Microsoft Visual Studio Build Tools 2019 (x86, x64, arm, arm64)

This may also support compilers shipped with compatible Visual Studio versions.
"""
if platform.system() == 'Windows':
    ...
else:
    class winreg:
        HKEY_USERS = ...
        HKEY_CURRENT_USER = ...
        HKEY_LOCAL_MACHINE = ...
        HKEY_CLASSES_ROOT = ...
    
    
    environ = ...
_msvc9_suppress_errors = ...
def msvc9_find_vcvarsall(version): # -> str | Any:
    """
    Patched "distutils.msvc9compiler.find_vcvarsall" to use the standalone
    compiler build for Python
    (VCForPython / Microsoft Visual C++ Compiler for Python 2.7).

    Fall back to original behavior when the standalone compiler is not
    available.

    Redirect the path of "vcvarsall.bat".

    Parameters
    ----------
    version: float
        Required Microsoft Visual C++ version.

    Return
    ------
    str
        vcvarsall.bat path
    """
    ...

def msvc9_query_vcvarsall(ver, arch=..., *args, **kwargs): # -> Any | dict[str, str]:
    """
    Patched "distutils.msvc9compiler.query_vcvarsall" for support extra
    Microsoft Visual C++ 9.0 and 10.0 compilers.

    Set environment without use of "vcvarsall.bat".

    Parameters
    ----------
    ver: float
        Required Microsoft Visual C++ version.
    arch: str
        Target architecture.

    Return
    ------
    dict
        environment
    """
    ...

PLAT_SPEC_TO_RUNTIME = ...
def msvc14_get_vc_env(plat_spec): # -> dict[str | Unknown, str | Unknown] | dict[str, str]:
    """
    Patched "distutils._msvccompiler._get_vc_env" for support extra
    Microsoft Visual C++ 14.X compilers.

    Set environment without use of "vcvarsall.bat".

    Parameters
    ----------
    plat_spec: str
        Target architecture.

    Return
    ------
    dict
        environment
    """
    ...

def msvc14_gen_lib_options(*args, **kwargs): # -> Any:
    """
    Patched "distutils._msvccompiler.gen_lib_options" for fix
    compatibility between "numpy.distutils" and "distutils._msvccompiler"
    (for Numpy < 1.11.2)
    """
    ...

class PlatformInfo:
    """
    Current and Target Architectures information.

    Parameters
    ----------
    arch: str
        Target architecture.
    """
    current_cpu = ...
    def __init__(self, arch) -> None:
        ...
    
    @property
    def target_cpu(self):
        """
        Return Target CPU architecture.

        Return
        ------
        str
            Target CPU
        """
        ...
    
    def target_is_x86(self):
        """
        Return True if target CPU is x86 32 bits..

        Return
        ------
        bool
            CPU is x86 32 bits
        """
        ...
    
    def current_is_x86(self): # -> bool:
        """
        Return True if current CPU is x86 32 bits..

        Return
        ------
        bool
            CPU is x86 32 bits
        """
        ...
    
    def current_dir(self, hidex86=..., x64=...): # -> str:
        """
        Current platform specific subfolder.

        Parameters
        ----------
        hidex86: bool
            return '' and not '\x86' if architecture is x86.
        x64: bool
            return '\x64' and not '\amd64' if architecture is amd64.

        Return
        ------
        str
            subfolder: '\target', or '' (see hidex86 parameter)
        """
        ...
    
    def target_dir(self, hidex86=..., x64=...): # -> Literal['', '\\x64']:
        r"""
        Target platform specific subfolder.

        Parameters
        ----------
        hidex86: bool
            return '' and not '\x86' if architecture is x86.
        x64: bool
            return '\x64' and not '\amd64' if architecture is amd64.

        Return
        ------
        str
            subfolder: '\current', or '' (see hidex86 parameter)
        """
        ...
    
    def cross_dir(self, forcex86=...): # -> str:
        r"""
        Cross platform specific subfolder.

        Parameters
        ----------
        forcex86: bool
            Use 'x86' as current architecture even if current architecture is
            not x86.

        Return
        ------
        str
            subfolder: '' if target architecture is current architecture,
            '\current_target' if not.
        """
        ...
    


class RegistryInfo:
    """
    Microsoft Visual Studio related registry information.

    Parameters
    ----------
    platform_info: PlatformInfo
        "PlatformInfo" instance.
    """
    HKEYS = ...
    def __init__(self, platform_info) -> None:
        ...
    
    @property
    def visualstudio(self): # -> Literal['VisualStudio']:
        """
        Microsoft Visual Studio root registry key.

        Return
        ------
        str
            Registry key
        """
        ...
    
    @property
    def sxs(self): # -> str:
        """
        Microsoft Visual Studio SxS registry key.

        Return
        ------
        str
            Registry key
        """
        ...
    
    @property
    def vc(self): # -> str:
        """
        Microsoft Visual C++ VC7 registry key.

        Return
        ------
        str
            Registry key
        """
        ...
    
    @property
    def vs(self): # -> str:
        """
        Microsoft Visual Studio VS7 registry key.

        Return
        ------
        str
            Registry key
        """
        ...
    
    @property
    def vc_for_python(self): # -> Literal['DevDiv\\VCForPython']:
        """
        Microsoft Visual C++ for Python registry key.

        Return
        ------
        str
            Registry key
        """
        ...
    
    @property
    def microsoft_sdk(self): # -> Literal['Microsoft SDKs']:
        """
        Microsoft SDK registry key.

        Return
        ------
        str
            Registry key
        """
        ...
    
    @property
    def windows_sdk(self): # -> str:
        """
        Microsoft Windows/Platform SDK registry key.

        Return
        ------
        str
            Registry key
        """
        ...
    
    @property
    def netfx_sdk(self): # -> str:
        """
        Microsoft .NET Framework SDK registry key.

        Return
        ------
        str
            Registry key
        """
        ...
    
    @property
    def windows_kits_roots(self): # -> Literal['Windows Kits\\Installed Roots']:
        """
        Microsoft Windows Kits Roots registry key.

        Return
        ------
        str
            Registry key
        """
        ...
    
    def microsoft(self, key, x86=...): # -> str:
        """
        Return key in Microsoft software registry.

        Parameters
        ----------
        key: str
            Registry key path where look.
        x86: str
            Force x86 software registry.

        Return
        ------
        str
            Registry key
        """
        ...
    
    def lookup(self, key, name): # -> None:
        """
        Look for values in registry in Microsoft software registry.

        Parameters
        ----------
        key: str
            Registry key path where look.
        name: str
            Value name to find.

        Return
        ------
        str
            value
        """
        ...
    


class SystemInfo:
    """
    Microsoft Windows and Visual Studio related system information.

    Parameters
    ----------
    registry_info: RegistryInfo
        "RegistryInfo" instance.
    vc_ver: float
        Required Microsoft Visual C++ version.
    """
    WinDir = ...
    ProgramFiles = ...
    ProgramFilesx86 = ...
    def __init__(self, registry_info, vc_ver=...) -> None:
        ...
    
    def find_reg_vs_vers(self): # -> List[Unknown]:
        """
        Find Microsoft Visual Studio versions available in registry.

        Return
        ------
        list of float
            Versions
        """
        ...
    
    def find_programdata_vs_vers(self): # -> dict[Unknown, Unknown]:
        r"""
        Find Visual studio 2017+ versions from information in
        "C:\ProgramData\Microsoft\VisualStudio\Packages\_Instances".

        Return
        ------
        dict
            float version as key, path as value.
        """
        ...
    
    @property
    def VSInstallDir(self): # -> str:
        """
        Microsoft Visual Studio directory.

        Return
        ------
        str
            path
        """
        ...
    
    @property
    def VCInstallDir(self): # -> str:
        """
        Microsoft Visual C++ directory.

        Return
        ------
        str
            path
        """
        ...
    
    @property
    def WindowsSdkVersion(self): # -> tuple[Literal['7.0'], Literal['6.1'], Literal['6.0a']] | tuple[Literal['7.1'], Literal['7.0a']] | tuple[Literal['8.0'], Literal['8.0a']] | tuple[Literal['8.1'], Literal['8.1a']] | tuple[Literal['10.0'], Literal['8.1']] | None:
        """
        Microsoft Windows SDK versions for specified MSVC++ version.

        Return
        ------
        tuple of str
            versions
        """
        ...
    
    @property
    def WindowsSdkLastVersion(self): # -> str:
        """
        Microsoft Windows SDK last version.

        Return
        ------
        str
            version
        """
        ...
    
    @property
    def WindowsSdkDir(self): # -> str:
        """
        Microsoft Windows SDK directory.

        Return
        ------
        str
            path
        """
        ...
    
    @property
    def WindowsSDKExecutablePath(self): # -> None:
        """
        Microsoft Windows SDK executable directory.

        Return
        ------
        str
            path
        """
        ...
    
    @property
    def FSharpInstallDir(self): # -> Literal['']:
        """
        Microsoft Visual F# directory.

        Return
        ------
        str
            path
        """
        ...
    
    @property
    def UniversalCRTSdkDir(self): # -> Literal[''] | None:
        """
        Microsoft Universal CRT SDK directory.

        Return
        ------
        str
            path
        """
        ...
    
    @property
    def UniversalCRTSdkLastVersion(self): # -> str:
        """
        Microsoft Universal C Runtime SDK last version.

        Return
        ------
        str
            version
        """
        ...
    
    @property
    def NetFxSdkVersion(self): # -> tuple[Literal['4.7.2'], Literal['4.7.1'], Literal['4.7'], Literal['4.6.2'], Literal['4.6.1'], Literal['4.6'], Literal['4.5.2'], Literal['4.5.1'], Literal['4.5']] | tuple[()]:
        """
        Microsoft .NET Framework SDK versions.

        Return
        ------
        tuple of str
            versions
        """
        ...
    
    @property
    def NetFxSdkDir(self): # -> Literal['']:
        """
        Microsoft .NET Framework SDK directory.

        Return
        ------
        str
            path
        """
        ...
    
    @property
    def FrameworkDir32(self): # -> str:
        """
        Microsoft .NET Framework 32bit directory.

        Return
        ------
        str
            path
        """
        ...
    
    @property
    def FrameworkDir64(self): # -> str:
        """
        Microsoft .NET Framework 64bit directory.

        Return
        ------
        str
            path
        """
        ...
    
    @property
    def FrameworkVersion32(self): # -> tuple[Unknown | str, Literal['v4.0']] | tuple[Unknown | str, Literal['v3.5']] | tuple[Literal['v3.5'], Literal['v2.0.50727']] | tuple[Literal['v3.0'], Literal['v2.0.50727']] | None:
        """
        Microsoft .NET Framework 32bit versions.

        Return
        ------
        tuple of str
            versions
        """
        ...
    
    @property
    def FrameworkVersion64(self): # -> tuple[Unknown | str, Literal['v4.0']] | tuple[Unknown | str, Literal['v3.5']] | tuple[Literal['v3.5'], Literal['v2.0.50727']] | tuple[Literal['v3.0'], Literal['v2.0.50727']] | None:
        """
        Microsoft .NET Framework 64bit versions.

        Return
        ------
        tuple of str
            versions
        """
        ...
    


class EnvironmentInfo:
    """
    Return environment variables for specified Microsoft Visual C++ version
    and platform : Lib, Include, Path and libpath.

    This function is compatible with Microsoft Visual C++ 9.0 to 14.X.

    Script created by analysing Microsoft environment configuration files like
    "vcvars[...].bat", "SetEnv.Cmd", "vcbuildtools.bat", ...

    Parameters
    ----------
    arch: str
        Target architecture.
    vc_ver: float
        Required Microsoft Visual C++ version. If not set, autodetect the last
        version.
    vc_min_ver: float
        Minimum Microsoft Visual C++ version.
    """
    def __init__(self, arch, vc_ver=..., vc_min_ver=...) -> None:
        ...
    
    @property
    def vs_ver(self):
        """
        Microsoft Visual Studio.

        Return
        ------
        float
            version
        """
        ...
    
    @property
    def vc_ver(self): # -> float:
        """
        Microsoft Visual C++ version.

        Return
        ------
        float
            version
        """
        ...
    
    @property
    def VSTools(self): # -> list[str]:
        """
        Microsoft Visual Studio Tools.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def VCIncludes(self): # -> list[str]:
        """
        Microsoft Visual C++ & Microsoft Foundation Class Includes.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def VCLibraries(self): # -> list[str]:
        """
        Microsoft Visual C++ & Microsoft Foundation Class Libraries.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def VCStoreRefs(self): # -> list[str]:
        """
        Microsoft Visual C++ store references Libraries.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def VCTools(self): # -> list[str]:
        """
        Microsoft Visual C++ Tools.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def OSLibraries(self): # -> list[str]:
        """
        Microsoft Windows SDK Libraries.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def OSIncludes(self): # -> list[str]:
        """
        Microsoft Windows SDK Include.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def OSLibpath(self): # -> list[Unknown]:
        """
        Microsoft Windows SDK Libraries Paths.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def SdkTools(self): # -> list[str | Unknown]:
        """
        Microsoft Windows SDK Tools.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def SdkSetup(self): # -> list[str]:
        """
        Microsoft Windows SDK Setup.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def FxTools(self): # -> list[Unknown]:
        """
        Microsoft .NET Framework Tools.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def NetFxSDKLibraries(self): # -> list[str]:
        """
        Microsoft .Net Framework SDK Libraries.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def NetFxSDKIncludes(self): # -> list[str]:
        """
        Microsoft .Net Framework SDK Includes.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def VsTDb(self): # -> list[str]:
        """
        Microsoft Visual Studio Team System Database.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def MSBuild(self): # -> list[str]:
        """
        Microsoft Build Engine.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def HTMLHelpWorkshop(self): # -> list[str]:
        """
        Microsoft HTML Help Workshop.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def UCRTLibraries(self): # -> list[str]:
        """
        Microsoft Universal C Runtime SDK Libraries.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def UCRTIncludes(self): # -> list[str]:
        """
        Microsoft Universal C Runtime SDK Include.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def FSharp(self): # -> list[Unknown | str]:
        """
        Microsoft Visual F#.

        Return
        ------
        list of str
            paths
        """
        ...
    
    @property
    def VCRuntimeRedist(self): # -> str | None:
        """
        Microsoft Visual C++ runtime redistributable dll.

        Return
        ------
        str
            path
        """
        ...
    
    def return_env(self, exists=...): # -> dict[str, str]:
        """
        Return environment dict.

        Parameters
        ----------
        exists: bool
            It True, only return existing paths.

        Return
        ------
        dict
            environment
        """
        ...
    


