"""
This type stub file was generated by pyright.
"""

def decompose(path): # -> str | bytes:
    ...

def filesys_decode(path): # -> str | None:
    """
    Ensure that the given path is decoded,
    NONE when no expected encoding works
    """
    ...

def try_encode(string, enc): # -> None:
    "turn unicode encoding into a functional routine"
    ...

