"""
This type stub file was generated by pyright.
"""

"""Wheels support."""
WHEEL_NAME = ...
NAMESPACE_PACKAGE_INIT = ...
def unpack(src_dir, dst_dir): # -> None:
    '''Move everything under `src_dir` to `dst_dir`, and delete the former.'''
    ...

class Wheel:
    def __init__(self, filename) -> None:
        ...
    
    def tags(self): # -> product[Tuple[Unknown, Unknown, Unknown]]:
        '''List tags (py_version, abi, platform) supported by this wheel.'''
        ...
    
    def is_compatible(self): # -> bool:
        '''Is the wheel is compatible with the current platform?'''
        ...
    
    def egg_name(self): # -> str:
        ...
    
    def get_dist_info(self, zf):
        ...
    
    def install_as_egg(self, destination_eggdir): # -> None:
        '''Install wheel as an egg directory.'''
        ...
    


