"""
This type stub file was generated by pyright.
"""

def windows_only(func): # -> (*args: Unknown, **kwargs: Unknown) -> None:
    ...

@windows_only
def hide_file(path): # -> None:
    """
    Set the hidden attribute on a file or directory.

    From http://stackoverflow.com/questions/19622133/

    `path` must be text.
    """
    ...

