"""
This type stub file was generated by pyright.
"""

from IPython.core.displayhook import DisplayHook

"""Terminal input and output prompts."""
class Prompts:
    def __init__(self, shell) -> None:
        ...
    
    def vi_mode(self): # -> str:
        ...
    
    def in_prompt_tokens(self): # -> list[tuple[_TokenType, str] | tuple[_TokenType, Literal['In [']] | tuple[_TokenType, Literal[']: ']]]:
        ...
    
    def continuation_prompt_tokens(self, width=...): # -> list[tuple[_TokenType, str | Unknown]]:
        ...
    
    def rewrite_prompt_tokens(self): # -> list[tuple[_TokenType, str]]:
        ...
    
    def out_prompt_tokens(self): # -> list[tuple[_TokenType, Literal['Out[']] | tuple[_TokenType, str] | tuple[_TokenType, Literal[']: ']]]:
        ...
    


class ClassicPrompts(Prompts):
    def in_prompt_tokens(self): # -> list[tuple[_TokenType, Literal['>>> ']]]:
        ...
    
    def continuation_prompt_tokens(self, width=...): # -> list[tuple[_TokenType, Literal['... ']]]:
        ...
    
    def rewrite_prompt_tokens(self): # -> list[Unknown]:
        ...
    
    def out_prompt_tokens(self): # -> list[Unknown]:
        ...
    


class RichPromptDisplayHook(DisplayHook):
    """Subclass of base display hook using coloured prompt"""
    def write_output_prompt(self): # -> None:
        ...
    
    def write_format_data(self, format_dict, md_dict=...) -> None:
        ...
    


