---
title: "PyShiny UI parity"
output: html_document
---

## Page layouts

✓ `navbarPage()` -> `page_navbar()`
✓ `fluidPage()` -> `page_fluid()`
✓ `fixedPage()`-> `page_fixed()`
✓ `bootstrapPage()`-> `page_bootstrap()`
`fillPage()`-> `page_fill()`
`htmlTemplate()`-> `page_template()`

## Layout, panels, other UI

✓ `sidebarLayout()` -> `layout_sidebar()`
✓ `sidebarPanel()` -> `panel_sidebar()`
✓ `mainPanel()` -> `panel_main()`
✓ `titlePanel()` -> `panel_title()`
✓ `wellPanel()` -> `panel_well()`
✓ `absolutePanel()` -> `panel_absolute()`
✓ `fixedPanel()` -> `panel_fixed()`
✓ `conditionalPanel()` -> `panel_conditional()`
  * Needs `NS()`
✓ `fluidRow()` / `fixedRow()` -> `row()`
✓ `column()` -> `col()`
✓ `helpText()` -> `help_text()`
`fillRow()` -> `row_fill()`
`fillCol()` -> `col_fill()`
`inputPanel()` -> `panel_inputs()`
  * Needs `flowLayout()`

`verticalLayout()` ->
`splitLayout()` (Replace these with a flexbox wrapper?)
`flowLayout()` (not needed? Use flexbox instead?)

## Tabs

✓ `tabsetPanel()` -> `navset_tab()`/`navset_pill()`
✓ `navlistPanel()` -> `navset_pill_list()`
✓ `tabPanel()` -> `nav()`
✓ `navbarMenu()` -> `nav_menu()`
`tabPanelBody()` -> `navs_content()`
`insertTab()`
`appendTab()`
`showTab()`
`removeTab()`
`hideTab()`
`prependTab()`

## Inputs

`selectInput()` -> `input_select()`
`selectizeInput()` -> `input_selectize()`
✓ `sliderInput()` -> `input_slider()`
  `animationOptions()`
✓ `dateInput()` -> `input_date()`
✓ `dateRangeInput()` -> `input_date_range()`
✓ `checkboxInput()` -> `input_checkbox()`
✓ `checkboxGroupInput()` -> `input_checkbox_group()`
✓ `textInput()` ->  `input_text()`
✓ `numericInput()` -> `input_numeric()`
✓ `passwordInput()` -> `input_password()`
✓ `textAreaInput()` -> `input_text_area()`
✓ `fileInput()` -> `input_file()`

✓ `actionLink()` -> `input_action_link()`
✓ `actionButton()` -> `input_action_button()`

`varSelectInput()` (not implemented)
`varSelectizeInput()` (not implemented)
`submitButton()` (not implemented)

## Modals, notifications, & progress

✓ `modalDialog()` -> `modal()`
✓ `modalButton()` -> `modal_button()`
✓ `showModal()` -> `modal_show()`
✓ `removeModal()` -> `modal_remove()`
✓ `showNotification()` -> `notification_show()`
✓ `removeNotification()` -> `notification_remove()`
✓ `Progress` -> `Progress()`
  `incProgress()` (not implemented)
  `setProgress()` (not implemented)
  `withProgress()` (not implemented)

## Output/render

✓ `imageOutput()`/`renderImage()`
✓ `plotOutput()`/`renderPlot()`
✓ `uiOutput()` / `renderUI()`
✓ `renderText()`/`textOutput()`
`tableOutput()` / `renderTable()`
`renderPrint()` / `verbatimTextOutput()`
`dataTableOutput()`/`renderDataTable()`
`outputOptions()`


## Dynamic UI

`insertUI()`
  * Needs `session.on_flush()`
`removeUI()`
  * Needs `session.on_flush()`

## Input updating

Needs `session$sendInputMessage()`

`updateNavbarPage()`
`updateTabsetPanel()`
`updateSliderInput()`
`updateTextInput()`
`updateNumericInput()`
`updateNavlistPanel()`
`updateActionLink()`
`updateActionButton()`
`updateDateInput()`
`updateDateRangeInput()`
`updateRadioButtons()`
`updateCheckboxInput()`
`updateSelectInput()`
`updateSelectizeInput()`
`updateCheckboxGroupInput()`

## Input handlers

`registerInputHandler()`
`removeInputHandler()`

## Uploads & downloads

`downloadButton()`
`downloadLink()`
`downloadHandler()`

## Dependencies

✓ `createWebDependency()` -> `create_web_dependency()`
`addResourcePath()`
`removeResourcePath()`
`resourcePaths()`
`suppressDependencies()`

## Misc

`withMathJax()`
`markdown()`
`icon()`
`validateCssUnit()`
`safeError()`
`httpResponse()`

## Theming

`getCurrentOutputInfo()`
`bootstrapLib()`
`getCurrentTheme()`
`registerThemeDependency()`

## Query strings

`getQueryString()`
`parseQueryString()`
`getUrlHash()`
`updateQueryString()`

## Validation

`need()`
`req()`
`validate()`
`isTruthy()`

# Inclusion helpers

`includeCSS()`
`includeScript()`
`includeMarkdown()`
`includeHTML()`
`includeText()`

# Not included (v2?)

* Caching (`bindCache`)
* Bookmarking
* Server testing (`testServer`)
* Testing helpers (snap)
