"""
This type stub file was generated by pyright.
"""

"""
Color schemes for exception handling code in IPython.
"""
def exception_colors(): # -> ColorSchemeTable:
    """Return a color table with fields for exception reporting.

    The table is an instance of ColorSchemeTable with schemes added for
    'Neutral', 'Linux', 'LightBG' and 'NoColor' and fields for exception handling filled
    in.

    Examples:

    >>> ec = exception_colors()
    >>> ec.active_scheme_name
    ''
    >>> print(ec.active_colors)
    None

    Now we activate a color scheme:
    >>> ec.set_active_scheme('NoColor')
    >>> ec.active_scheme_name
    'NoColor'
    >>> sorted(ec.active_colors.keys())
    ['Normal', 'caret', 'em', 'excName', 'filename', 'filenameEm', 'line',
    'lineno', 'linenoEm', 'name', 'nameEm', 'normalEm', 'topline', 'vName',
    'val', 'valEm']
    """
    ...

class Deprec:
    def __init__(self, wrapped_obj) -> None:
        ...
    
    def __getattr__(self, name): # -> Any:
        ...
    


ExceptionColors = ...
