name: 'setup py-shiny'
description: 'Action that installs python, installs py-shiny dependencies, and installs py-shiny'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: "3.12"
runs:
  using: "composite"
  steps:
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          # # Caching with pip only saves ~15 seconds. Not work risks of confusion.
          # cache: 'pip'
          # cache-dependency-path: |
          #   setup.cfg

      - name: Install dependencies
        shell: bash
        run: |
          make install-ci

      - name: Install
        shell: bash
        run: |
          make install
