name: 'setup py-shiny'
description: 'Action that installs python, installs py-shiny dependencies, and installs py-shiny'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: "3.11"
runs:
  using: "composite"
  steps:
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Upgrade pip
        shell: bash
        run: python -m pip install --upgrade pip

      # TODO-future; Cache pip dependencies; See if installed library can be hashed

      - name: Install dependencies
        shell: bash
        run: |
          pip install https://github.com/rstudio/py-htmltools/tarball/main
          make install-deps

      - name: Install
        shell: bash
        run: |
          make install
