"""
This type stub file was generated by pyright.
"""

import sys
from distutils.command.bdist import bdist
from setuptools.command import install_scripts

if 'egg' not in bdist.format_commands:
    ...
