"""
This type stub file was generated by pyright.
"""

from . import tags

__license__ = ...
class document(tags.html):
  tagname = ...
  def __init__(self, title=..., doctype=..., request=...) -> None:
    '''
    Creates a new document instance. Accepts `title`, `doctype`, and `request` keyword arguments.
    '''
    ...
  
  def get_title(self):
    ...
  
  def set_title(self, title): # -> None:
    ...
  
  title = ...
  def add(self, *args):
    '''
    Adding tags to a document appends them to the <body>.
    '''
    ...
  
  def render(self, *args, **kwargs): # -> str:
    '''
    Creates a <title> tag if not present and renders the DOCTYPE and tag tree.
    '''
    ...
  
  __str__ = ...
  def __repr__(self): # -> Any:
    ...
  


