[build-system]
requires = ["setuptools>=40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "customOutputComponent"
version = "0.1"
dependencies = ["shiny >= 0.6.0"]

[tool.setuptools]
packages = ["customOutputComponent"]
include-package-data = true
zip-safe = false