"""
This type stub file was generated by pyright.
"""

from typing import Callable, Dict, List, Optional, Union

def package_dir(package: str) -> str:
  ...

class html_dependency:
  def __init__(self, name: str, version: str, src: Union[str, Dict[str, str]], script: Optional[Union[str, List[str], List[Dict[str, str]]]] = ..., stylesheet: Optional[Union[str, List[str], List[Dict[str, str]]]] = ..., package: Optional[str] = ..., all_files: bool = ..., meta: Optional[List[Dict[str, str]]] = ..., head: Optional[str] = ...) -> None:
    ...
  
  def render(self, src_type: str = ..., encode_path: Callable[[str], str] = ...) -> str:
    ...
  
  def __repr__(self): # -> str:
    ...
  
  def __str__(self) -> str:
    ...
  


