"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional

class tag:
  def __init__(self, *args: Any, _name: str, children: Optional[Any] = ..., **kwargs: Dict[str, str]) -> None:
    ...
  
  def __call__(self, *args: Any, **kwargs: Dict[str, str]) -> None:
    ...
  
  def append_attrs(self, **kwargs: Dict[str, str]) -> None:
    ...
  
  def append_children(self, *args: Dict[str, str]) -> None:
    ...
  
  def as_string(self) -> str:
    ...
  
  def show(self, renderer: str = ...) -> None:
    ...
  
  def render(self, indent: int = ..., eol: str = ...) -> str:
    ...
  
  def __str__(self) -> str:
    ...
  
  def __repr__(self) -> str:
    ...
  


class tag_list(tag):
  def __init__(self, *args) -> None:
    ...
  
  def render(self, indent: int = ..., eol: str = ...) -> str:
    ...
  


def tag_factory(_name: str) -> tag:
  ...

class tags_(Dict[str, tag]):
  def __init__(self) -> None:
    ...
  
  def __getattr__(self, name: str) -> tag:
    ...
  


tags = ...
