"""
This type stub file was generated by pyright.
"""

from typing import List

class html(str):
  def __new__(cls, *args: List[str]) -> str:
    ...
  


def html_escape(text: str, attr: bool = ...): # -> str:
  ...

def normalize_text(txt: str): # -> html | str:
  ...

