"""
This type stub file was generated by pyright.
"""

"""A fancy version of Python's builtin :func:`dir` function.
"""
def safe_hasattr(obj, attr): # -> bool:
    """In recent versions of Python, hasattr() only catches AttributeError.
    This catches all errors.
    """
    ...

def dir2(obj): # -> List[str | Unknown]:
    """dir2(obj) -> list of strings

    Extended version of the Python builtin dir(), which does a few extra
    checks.

    This version is guaranteed to return only a list of true strings, whereas
    dir() returns anything that objects inject into themselves, even if they
    are later not really valid for attribute access (many extension libraries
    have such bugs).
    """
    ...

def get_real_method(obj, name): # -> Any | MethodType | None:
    """Like getattr, but with a few extra sanity checks:

    - If obj is a class, ignore everything except class methods
    - Check if obj is a proxy that claims to have all attributes
    - Catch attribute access failing with any exception
    - Check that the attribute is a callable object

    Returns the method or None.
    """
    ...

