"""
This type stub file was generated by pyright.
"""

from tempfile import TemporaryDirectory

""" This module contains classes - NamedFileInTemporaryDirectory, TemporaryWorkingDirectory.

These classes add extra features such as creating a named file in temporary directory and
creating a context manager for the working directory which is also temporary.
"""
class NamedFileInTemporaryDirectory:
    def __init__(self, filename, mode=..., bufsize=..., **kwds) -> None:
        """
        Open a file named `filename` in a temporary directory.

        This context manager is preferred over `NamedTemporaryFile` in
        stdlib `tempfile` when one needs to reopen the file.

        Arguments `mode` and `bufsize` are passed to `open`.
        Rest of the arguments are passed to `TemporaryDirectory`.

        """
        ...
    
    def cleanup(self): # -> None:
        ...
    
    __del__ = ...
    def __enter__(self): # -> TextIOWrapper:
        ...
    
    def __exit__(self, type, value, traceback): # -> None:
        ...
    


class TemporaryWorkingDirectory(TemporaryDirectory):
    """
    Creates a temporary directory and sets the cwd to that directory.
    Automatically reverts to previous cwd upon cleanup.
    Usage example:

        with TemporaryWorkingDirectory() as tmpdir:
            ...
    """
    def __enter__(self):
        ...
    
    def __exit__(self, exc, value, tb): # -> None:
        ...
    


