"""
This type stub file was generated by pyright.
"""

import sys

"""distutils

The main package for the Python Module Distribution Utilities.  Normally
used from a setup script as

   from distutils.core import setup

   setup (...)
"""
__version__ = ...
local = ...
