#!/usr/bin/env Rscript

versions <- list()

# Use local lib path for installing packages so we don't pollute the user's library
# withr::local_temp_libpaths()

pak::pkg_install(c("rstudio/bslib@main", "rstudio/shiny@main", "rstudio/htmltools@main"))
# pak::pkg_install(c("cran::bslib", "cran::shiny"))

versions["shiny_html_deps"] <- as.character(packageVersion("shiny"))
versions["bslib"] <- as.character(packageVersion("bslib"))

pkg_source_version <- function(pkg_name) {
  pkg_info <- sessioninfo::package_info(pkg_name)
  pkg_info_list <- pkg_info[pkg_info$package == pkg_name, , drop = TRUE]
  pkg_info_list$source
}
write_json <- function(file, x, ..., pretty = TRUE, auto_unbox = TRUE) {
  jsonlite::write_json(
    c(
      list("note!" = "This file is auto-generated by scripts/htmlDependencies.R"),
      x
    ),
    file,
    ...,
    pretty = pretty, auto_unbox = auto_unbox
  )

}

bslib_version <- pkg_source_version("bslib")
shiny_version <- pkg_source_version("shiny")
htmltools_version <- pkg_source_version("htmltools")

library(htmltools)
library(bslib)

shiny_path <- fs::path(getwd(), "shiny")
www <- fs::path(shiny_path, "www")
www_shared <- fs::path(www, "shared")
x_www <- fs::path(shiny_path, "experimental", "www")
x_www_components <- fs::path(x_www, "bslib", "components")

# Copy over shiny's www/shared directory
copy_from_pkg <- function(pkg_name, pkg_dir, local_dir) {
  if (fs::dir_exists(local_dir)) fs::dir_delete(local_dir)
  fs::dir_create(local_dir)

  stopifnot(local_dir != ".")

  # Copy other folder into local parent folder
  fs::dir_copy(
    system.file(pkg_dir, package = pkg_name),
    dirname(local_dir)
  )
  # Rename folder to local folder name
  if (basename(local_dir) != basename(pkg_dir)) {
    file.rename(
      fs::path(dirname(local_dir), basename(pkg_dir)),
      local_dir
    )
  }
  # Save pkg version info
  write_json(
    fs::path(local_dir, "_versions.json"),
    list(
      package = pkg_name,
      version = pkg_source_version(pkg_name)
    )
  )
}


# Copy over bslib's components directory
copy_from_pkg("bslib", "components", x_www_components)
# Remove unused Sass files
fs::file_delete(
  fs::dir_ls(x_www_components, type = "file", regexp = "\\.scss$")
)
# Remove unused tag require
fs::file_delete(fs::path(x_www_components, "tag-require.js"))

# Copy over htmltools's fill directory
copy_from_pkg("htmltools", "fill", fs::path(x_www, "htmltools", "fill"))




# Copy over shiny's www/shared directory
copy_from_pkg("shiny", "www/shared", www_shared)

# Don't need legacy (hopefully)
fs::dir_delete(fs::path(www_shared, "legacy"))
# Don't need dataTables (hopefully)
fs::dir_delete(fs::path(www_shared, "datatables"))

# jQuery will come in via bslib (below)
fs::file_delete(
  fs::dir_ls(www_shared, type = "file", regexp = "jquery")
)

# Upgrade to Bootstrap 5 by default
deps <- bs_theme_dependencies(bs_theme(version = 5))
withr::with_options(
  list(htmltools.dir.version = FALSE),
  ignore <- lapply(deps, copyDependencyToDir, www_shared)
)
bs_ver <- names(bslib::versions())[bslib::versions() == "5"]
versions["bootstrap"] <- bs_ver
write_json(
  "shiny/www/shared/bootstrap/_version.json",
  list(
    shiny_version = shiny_version,
    bslib_version = bslib_version,
    htmltools_version = htmltools_version,
    bootstrap_version = bs_ver
  )
)

# This additional bs3compat HTMLDependency() only holds
# the JS shim for tab panel logic, which we don't need
# since we're generating BS5+ tab markup. Note, however,
# we still do have bs3compat's CSS on the page, which
# comes in via the bootstrap HTMLDependency()
fs::dir_delete(fs::path(www_shared, "bs3compat"))

requirejs_version <- "2.3.6"
versions["requirejs"] <- requirejs_version
requirejs <- fs::path(www_shared, "requirejs")
fs::dir_create(requirejs)
download.file(
  paste0("https://cdnjs.cloudflare.com/ajax/libs/require.js/", requirejs_version, "/require.min.js"),
  fs::path(requirejs, "require.min.js")
)

shims <- fs::path(getwd(), "scripts", "define-shims.js")

cat(
  "\n\n",
  paste(readLines(shims), collapse = "\n"),
  file = fs::path(requirejs, "require.min.js"),
  append = TRUE
)


version_vars <- paste0(names(versions), " = ", "\"", versions, "\"\n", collapse = "")
version_all <- paste0(
  collapse = "",
  "__all__ = (\n",
  paste0("    \"", names(versions), "\",\n", collapse = ""),
  ")\n"
)
cat(
  file = fs::path(shiny_path, "_versions.py"),
  version_vars,
  "\n",
  version_all,
  sep = ""
)
