# Page functions



# express.ui.page_opts { #shiny.express.ui.page_opts }

`express.ui.page_opts(title=MISSING, lang=MISSING, page_fn=MISSING, fillable=MISSING, full_width=MISSING)`

Set page-level options for the current app.

The arguments to this function get passed to [](:func:`~shiny.ui.page_auto`).

## Parameters

<code><span class="parameter-name">title</span><span class="parameter-annotation-sep">:</span> <span class="parameter-annotation">[str](`str`) \| [MISSING_TYPE](`shiny.types.MISSING_TYPE`)</span> <span class="parameter-default-sep">=</span> <span class="parameter-default">MISSING</span></code>

:   The browser window title (defaults to the host URL of the page).

<code><span class="parameter-name">lang</span><span class="parameter-annotation-sep">:</span> <span class="parameter-annotation">[str](`str`) \| [MISSING_TYPE](`shiny.types.MISSING_TYPE`)</span> <span class="parameter-default-sep">=</span> <span class="parameter-default">MISSING</span></code>

:   ISO 639-1 language code for the HTML page, such as ``"en"`` or ``"ko"``. This
    will be used as the lang in the ``<html>`` tag, as in ``<html lang="en">``. The
    default, `None`, results in an empty string.

<code><span class="parameter-name">fillable</span><span class="parameter-annotation-sep">:</span> <span class="parameter-annotation">[bool](`bool`) \| [MISSING_TYPE](`shiny.types.MISSING_TYPE`)</span> <span class="parameter-default-sep">=</span> <span class="parameter-default">MISSING</span></code>

:   If there is a top-level sidebar or nav, then the value is passed through to the
    [](:func:`~shiny.ui.page_sidebar`) or [](:func:`~shiny.ui.page_navbar`) function.
    Otherwise, if ``True``, use [](:func:`~shiny.ui.page_fillable`), where the content
    fills the window; if ``False`` (the default), the value of ``full_width`` will
    determine which page function is used.

<code><span class="parameter-name">full_width</span><span class="parameter-annotation-sep">:</span> <span class="parameter-annotation">[bool](`bool`) \| [MISSING_TYPE](`shiny.types.MISSING_TYPE`)</span> <span class="parameter-default-sep">=</span> <span class="parameter-default">MISSING</span></code>

:   This has an effect only if there are no sidebars or top-level navs, and
    ``fillable`` is ``False``. If this is ``False`` (the default), use use
    [](:func:`~shiny.ui.page_fixed`); if ``True``, use [](:func:`~shiny.ui.page_fillable`).

<code><span class="parameter-name">page_fn</span><span class="parameter-annotation-sep">:</span> <span class="parameter-annotation">[Callable](`typing.Callable`)\[..., [Tag](`htmltools.Tag`)\] \| None \| [MISSING_TYPE](`shiny.types.MISSING_TYPE`)</span> <span class="parameter-default-sep">=</span> <span class="parameter-default">MISSING</span></code>

:   The page function to use. If ``None`` (the default), will automatically choose
    one based on the arguments provided. If not ``None``, this will override all
    heuristics for choosing page functions.