# ui.ShowcaseLayout { #shiny.ui.ShowcaseLayout }

`ui.ShowcaseLayout(self, *, class_, width='33%', width_full_screen='1fr', height=None, height_full_screen=None, max_height='100px', max_height_full_screen='67%')`

Showcase layout

Base layout information utilized to display [](:func:`~shiny.ui.value_box`)&#x27;s `showcase` value.



## See Also

* [](:func:`~shiny.ui.showcase_left_center`)
* [](:func:`~shiny.ui.showcase_top_right`)
* [](:func:`~shiny.ui.showcase_bottom`)
* [](:func:`~shiny.ui.value_box`)

## Attributes

| Name | Description |
| --- | --- |
| [class_](#shiny.ui.ShowcaseLayout.class_) | CSS class to set on the layout |
| [height](#shiny.ui.ShowcaseLayout.height) | Height of the showcase area |
| [height_full_screen](#shiny.ui.ShowcaseLayout.height_full_screen) | Height of the showcase area when the value box is full screen |
| [max_height](#shiny.ui.ShowcaseLayout.max_height) | Maximum height of the showcase area |
| [max_height_full_screen](#shiny.ui.ShowcaseLayout.max_height_full_screen) | Maximum height of the showcase area when the value box is full screen |
| [width](#shiny.ui.ShowcaseLayout.width) | Width of the showcase area |
| [width_full_screen](#shiny.ui.ShowcaseLayout.width_full_screen) | Width of the showcase area when the value box is full screen |