project:
  type: website
  output-dir: _site

format:
  html:
    toc: true

website:
  title: "Shiny for Python (dev version)"
  description: "A Python package for writing interactive web applications."
  repo-url: https://github.com/rstudio/py-shiny
  repo-actions: [issue]
  page-navigation: true
  navbar:
    background: primary
    pinned: true
    search: true
    left:
      - text: "API"
        file: api/index.qmd
    right:
      - icon: github
        href: https://github.com/rstudio/py-shiny
        aria-label: Shiny for Python on GitHub

metadata-files:
  - api/_sidebar.yml

filters:
  - shinylive
  - interlinks

interlinks:
  sources:
    python:
      url: https://docs.python.org/3/
