# Generated by scripts/htmlDependencies.R: do not edit by hand

from __future__ import annotations

from typing import Literal

VERSION_PRISM_CODE_EDITOR = "0.9.0.9002"

CodeEditorBundledLanguage = Literal[
    "bash",
    "cpp",
    "css",
    "diff",
    "docker",
    "ini",
    "javascript",
    "json",
    "julia",
    "latex",
    "markdown",
    "markup",
    "python",
    "r",
    "rust",
    "sass",
    "scss",
    "sql",
    "toml",
    "typescript",
    "xml",
    "yaml",
]

CodeEditorTheme = Literal[
    "atom-one-dark",
    "dracula",
    "github-dark",
    "github-dark-dimmed",
    "github-light",
    "night-owl",
    "night-owl-light",
    "prism",
    "prism-okaidia",
    "prism-solarized-light",
    "prism-tomorrow",
    "prism-twilight",
    "vs-code-dark",
    "vs-code-light",
]
