name: End-to-End Tests

on:
  push:
    branches: ["main", "rc-*"]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  playwright-shiny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10", "3.9", "3.8"]
        browser: ["chromium", "firefox", "webkit"]
        exclude:
          - python-version: ${{ github.event.pull_request.draft && '3.11' }}
          - python-version: ${{ github.event.pull_request.draft && '3.10' }}
          - python-version: ${{ github.event.pull_request.draft && '3.9' }}
          - browser: ${{ github.event.pull_request.draft && 'firefox' }}
          - browser: ${{ github.event.pull_request.draft && 'webkit' }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Setup py-shiny
        uses: ./.github/py-shiny/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Determine browsers for testing
        uses: ./.github/py-shiny/pytest-browsers
        id: browsers
        with:
          browser: ${{ matrix.browser }}

      - name: Run End-to-End tests
        timeout-minutes: 20
        run: |
          . venv/bin/activate && \
            make playwright-shiny SUB_FILE=". -vv --numprocesses 4" ${{ steps.browsers.outputs.browsers }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "playright-shiny-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.browser }}-results"
          path: test-results/
          retention-days: 5

  playwright-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10", "3.9", "3.8"]
        browser: ["chromium", "firefox", "webkit"]
        exclude:
          - python-version: ${{ github.event.pull_request.draft && '3.11' }}
          - python-version: ${{ github.event.pull_request.draft && '3.10' }}
          - python-version: ${{ github.event.pull_request.draft && '3.9' }}
          - browser: ${{ github.event.pull_request.draft && 'firefox' }}
          - browser: ${{ github.event.pull_request.draft && 'webkit' }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Setup py-shiny
        uses: ./.github/py-shiny/setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Determine browsers for testing
        uses: ./.github/py-shiny/pytest-browsers
        id: browsers
        with:
          browser: ${{ matrix.browser }}

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm
          cache-dependency-path: examples/brownian/shinymediapipe/package-lock.json
      - name: Install node.js package
        working-directory: examples/brownian/shinymediapipe
        run: |
          npm ci

      - name: Run example app tests
        timeout-minutes: 20
        run: |
          . venv/bin/activate && \
            make playwright-examples SUB_FILE=". -vv --numprocesses 4" ${{ steps.browsers.outputs.browsers }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "playright-examples-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.browser }}-results"
          path: test-results/
          retention-days: 5

  playwright-deploys-precheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Matches deploy server python version
        python-version: ["3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Setup py-shiny
        uses: ./.github/py-shiny/setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Determine browsers for testing
        uses: ./.github/py-shiny/pytest-browsers
        id: browsers
        with:
          all-browsers: ${{ ! github.event.pull_request.draft }}

      - name: Install rsconnect
        run: |
          . venv/bin/activate && \
            uv pip install "rsconnect_python @ git+https://github.com/rstudio/rsconnect-python.git"

      - name: Test that deployable example apps work
        timeout-minutes: 5 # ~10s locally
        env:
          DEPLOY_APPS: "false"
        run: |
          . venv/bin/activate && \
            make playwright-deploys SUB_FILE=". -vv"

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "playright-examples-${{ runner.os }}-${{ matrix.python-version }}-results"
          path: test-results/
          retention-days: 5
