name: End-to-End Tests

on:
  push:
    branches: ["main", "rc-*"]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      is-draft: ${{ steps.is-draft.outputs.value }}
      python-versions: ${{ steps.python-versions.outputs.values }}
      browsers: ${{ steps.browsers.outputs.values }}
    steps:
      - name: Is Draft
        id: is-draft
        run: |
          echo 'value=${{ github.event.pull_request.draft }}' > $GITHUB_OUTPUT

      - name: Python versions
        id: python-versions
        run: |
          if [[ ${{ steps.is-draft.outputs.value }} == "true" ]]; then
            echo 'values=["3.12", "3.11", "3.10", "3.9", "3.8"]' > $GITHUB_OUTPUT
          else
            echo 'values=["3.12", "3.8"]' > $GITHUB_OUTPUT
          fi

      - name: Browsers
        id: browsers
        run: |
          if [[ ${{ steps.is-draft.outputs.value }} == "true" ]]; then
            echo 'values=["chromium", "firefox", "webkit"]' > $GITHUB_OUTPUT
          else
            echo 'values=["chromium"]' > $GITHUB_OUTPUT
          fi

  playwright-shiny:
    runs-on: ${{ matrix.os }}
    needs: [setup]
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ${{ fromJson(needs.setup.outputs.python-versions) }}
        browser: ${{ fromJson(needs.setup.outputs.browsers) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Setup py-shiny
        uses: ./.github/py-shiny/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Determine browsers for testing
        uses: ./.github/py-shiny/pytest-browsers
        id: browsers
        with:
          browser: ${{ matrix.browser }}

      # TODO-barret remove
      - name: Display browser
        shell: bash
        run: echo '${{ steps.browsers.outputs.browsers }}'

      - name: Run End-to-End tests
        timeout-minutes: 20
        run: |
          make playwright-shiny SUB_FILE=". -vv" ${{ steps.browsers.outputs.browsers }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "playright-shiny-${{ matrix.os }}-${{ matrix.python-version }}-results"
          path: test-results/
          retention-days: 5

  playwright-examples:
    runs-on: ${{ matrix.os }}
    needs: [setup]
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ${{ fromJson(needs.setup.outputs.python-versions) }}
        browser: ${{ fromJson(needs.setup.outputs.browsers) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Setup py-shiny
        uses: ./.github/py-shiny/setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Determine browsers for testing
        uses: ./.github/py-shiny/pytest-browsers
        id: browsers
        with:
          browser: ${{ matrix.browser }}

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm
          cache-dependency-path: examples/brownian/shinymediapipe/package-lock.json
      - name: Install node.js package
        working-directory: examples/brownian/shinymediapipe
        run: |
          npm ci

      - name: Run example app tests
        timeout-minutes: 20
        run: |
          make playwright-examples SUB_FILE=". -vv" ${{ steps.browsers.outputs.browsers }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "playright-examples-${{ matrix.os }}-${{ matrix.python-version }}-results"
          path: test-results/
          retention-days: 5

  playwright-deploys-precheck:
    runs-on: ${{ matrix.os }}
    needs: [setup]
    strategy:
      matrix:
        # Matches deploy server python version
        python-version: ["3.10"]
        os: [ubuntu-latest]
        browser: ${{ fromJson(needs.setup.outputs.browsers) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Setup py-shiny
        uses: ./.github/py-shiny/setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Determine browsers for testing
        uses: ./.github/py-shiny/pytest-browsers
        id: browsers
        with:
          all-browsers: ${{ ! needs.setup.outputs.is-draft }}

      - name: Test that deployable example apps work
        timeout-minutes: 5 # ~10s locally
        env:
          DEPLOY_APPS: "false"
        run: |
          make playwright-deploys SUB_FILE=". -vv"

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "playright-examples-${{ matrix.os }}-${{ matrix.python-version }}-results"
          path: test-results/
          retention-days: 5
