name: Issue Management

on:
  issues:
    types: [opened]

jobs:
  triage_or_add_to_project:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the issue creator is a maintainer
        id: check_maintainer
        run: |
            IS_ADMIN=`gh api /repos/rstudio/py-shiny/collaborators/${{ github.event.issue.user.login }}/permission --jq='.user.permissions.admin'`
            echo "is_maintainer=$IS_ADMIN" >> "$GITHUB_OUTPUT"

      - name: Apply "needs triage" label to issues created by non-maintainers
        if: steps.check_maintainer.outputs.is_maintainer == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["needs-triage"]
            })
