name: Validate Testing Documentation for changes

on:
  pull_request:
    paths:
      - 'docs/_quartodoc-testing.yml'
      - 'shiny/playwright/controller/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-controller-changes:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for controller changes
        id: check-controller
        run: |
          # Check if any files in shiny/playwright/controller have changed
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q '^shiny/playwright/controller/'; then
            echo "controller_changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in shiny/playwright/controller directory"
          else
            echo "controller_changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected in shiny/playwright/controller directory"
          fi

      - name: Comment on PR about testing docs update
        if: steps.check-controller.outputs.controller_changed == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: testing-docs-update
          message: |
            🤖 **Testing Documentation Update Required**

            We detected changes in the `shiny/playwright/controller` directory. These changes may affect the testing documentation used by the `shiny add test` command.

            **Please run the following command to update the testing documentation:**

            ```bash
            make update-testing-docs
            ```

            <details><summary>Additional details</summary>

            This command will:
            1. Install repomix if not already installed
            2. Build the latest documentation with quartodoc
            3. Generate repomix output for testing docs
            4. Process the output to update the AI test generator documentation
            5. Clean up temporary files

            </details>

            This will ensure that the AI test generator has access to the latest controller API documentation.

            ---
            *This comment was automatically generated by the validate_testing_docs workflow.*

      - name: Remove comment when no controller changes
        if: steps.check-controller.outputs.controller_changed == 'false'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: testing-docs-update
          delete: true
